ENG-112113: Revert "target-i386: Enable "check" mode by default"
This reverts commit 15e41345906d29a319cc9cdf566347bf79134d24.

Rationale: libvirt tries to report the reason for failure by reading the log.
Having 'check' mode enabled causes the log to fill with inconsequential messages
that can cause more interesting error messages to fall off the bottom of
libvirt's buffer. This can hinder debugging.

Before:
  libvirtError: internal error: process exited while connecting to monitor: warning: host doesn't support requested feature: CPUID.01H:EDX.ds [bit 21]
  warning: host doesn't support requested feature: CPUID.01H:EDX.acpi [bit 22]
  warning: host doesn't support requested feature: CPUID.01H:EDX.ht [bit 28]
  warning: host doesn't support requested feature: CPUID.01H:EDX.tm [bit 29]
  warning: host doesn't support requested feature: CPUID.01H:EDX.pbe [bit 31]
  warning: host doesn't support requested feature: CPUID.01H:ECX.dtes64 [bit 2]
  warning: host doesn't support requested feature: CPUID.01H:ECX.monitor [bit 3]
  warning: host doesn't support requested feature: CPUID.01H:ECX.ds_cpl [bit 4]
  warning: host doesn't support requested feature: CPUID.01H:ECX.smx [bit 6]
  warning: host doesn't support requested feature: CPUID.01H:ECX.est [bit 7]
  warning: host doesn't support requested feature: CPUID.01H:ECX.tm2 [bit 8]
  warning: host doesn't support requested feature: CPUID.01H:ECX.xtpr [bit 14]
  warning: host doesn't support requested feature: CPUID.01H:ECX.

After:
  libvirtError: internal error: qemu unexpectedly closed the monitor: warning: bad stuff happened

Change-Id: I431ca23593aa9595f51bc839e561416aebba5282