e1000e: Fix build with gcc 4.6.3 and ust tracing
RH-Author: Xiao Wang <jasowang@redhat.com>
Message-id: <1469083246-12219-18-git-send-email-jasowang@redhat.com>
Patchwork-id: 71264
O-Subject: [RHEL7.3 qemu-kvm-rhev PATCH 17/19] e1000e: Fix build with gcc 4.6.3 and ust tracing
Bugzilla: 1343092
RH-Acked-by: Laszlo Ersek <lersek@redhat.com>
RH-Acked-by: Laurent Vivier <lvivier@redhat.com>
RH-Acked-by: Dmitry Fleytman <dfleytma@redhat.com>

From: Dmitry Fleytman <dmitry@daynix.com>

This patch fixes used-uninitialized false
positive while compiling with ust tracing
backend plus gcc 4.6.3:

hw/net/e1000e.c: In function ‘e1000e_io_write’:
hw/net/e1000e.c:170:39: error: ‘idx’ may be used uninitialized in this function [-Werror=uninitialized]
hw/net/e1000e.c: In function ‘e1000e_io_read’:
hw/net/e1000e.c:145:35: error: ‘idx’ may be used uninitialized in this function [-Werror=uninitialized]
cc1: all warnings being treated as errors
make: *** [hw/net/e1000e.o] Error 1

Signed-off-by: Dmitry Fleytman <dmitry@daynix.com>
Acked-by: Jason Wang <jasowang@redhat.com>
Message-id: 1465023763-10773-1-git-send-email-dmitry@daynix.com
Signed-off-by: Peter Maydell <peter.maydell@linaro.org>
(cherry picked from commit de5dca1b792ada25c29a95c8f84e01f4300aef9c)
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>