tools: kvm_stat: Powerpc related fixes
RH-Author: Laurent Vivier <lvivier@redhat.com>
Message-id: <1464800901-12761-1-git-send-email-lvivier@redhat.com>
Patchwork-id: 70525
O-Subject: [RHEV-7.3 qemu-kvm-rhev PATCH] tools: kvm_stat: Powerpc related fixes
Bugzilla: 1337033
RH-Acked-by: Miroslav Rezanina <mrezanin@redhat.com>
RH-Acked-by: David Gibson <dgibson@redhat.com>
RH-Acked-by: Thomas Huth <thuth@redhat.com>

From: Hemant Kumar <hemant@linux.vnet.ibm.com>

kvm_stat script is failing to execute on powerpc :
 # ./kvm_stat
Traceback (most recent call last):
  File "./kvm_stat", line 825, in <module>
    main()
  File "./kvm_stat", line 813, in main
    providers = get_providers(options)
  File "./kvm_stat", line 778, in get_providers
    providers.append(TracepointProvider())
  File "./kvm_stat", line 416, in __init__
    self.filters = get_filters()
  File "./kvm_stat", line 315, in get_filters
    if ARCH.exit_reasons:
AttributeError: 'ArchPPC' object has no attribute 'exit_reasons'

This is because, its trying to access a non-defined attribute.

Also, the IOCTL number of RESET is incorrect for powerpc. The correct
number has been added.

Signed-off-by: Hemant Kumar <hemant@linux.vnet.ibm.com>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>

This patch is an upstream commit in the kernel repo, but applied
downstream only in the qemu repo.

kvm_stat has moved to the kernel repo since:

    [qemu]  60b412d kvm_stat: Remove
    [linux] f9bc9e6 tools: Add kvm_stat vm monitor script

This patch is a backport of the patch applied to the kernel repo to
the qemu repo:

    [linux] c7d4fb5 tools: kvm_stat: Powerpc related fixes

The original patch was also posted on the qemu-devel ML:

    http://patchwork.ozlabs.org/patch/611965/

Signed-off-by: Laurent Vivier <lvivier@redhat.com>
Signed-off-by: Miroslav Rezanina <mrezanin@redhat.com>